var listList = ["christmas", "bread", "fletch", "football", "germain", "glenn", "irvine", "labartu", "mendel", "olsen", "shadow", "tech", "terminator", "tuffmuff", "vyrastas", "woody"];

var christmasList = [
    ["Devil May Cry HD","Cold Turkey - Fight Griffon a second time and prevail","http://www.playstationtrophies.org/images/trophies/1223/BD5.jpg"],
    ["Escape Plan","Starry Night - Earn 3 stars in every level","http://www.playstationtrophies.org/images/trophies/2405/9c2.jpg"],
    ["Far Cry 3: Blood Dragon","Nice Like Jesus - Finish all the Hostages Situations","http://www.playstationtrophies.org/images/trophies/2000/6ED.jpg"],
    ["Hell Yeah! Wrath of the Dead Rabbit","Good Santa! - Find a secret gift. \"You are gifted, sir!\"","http://www.playstationtrophies.org/images/trophies/1435/328.jpg"],
    ["LEGO The Lord Of The Rings","Don't tell the Elf... - Throw Gimli 30 times.","http://www.playstationtrophies.org/images/trophies/1535/E15.jpg"],
    ["Metro: Last Light","A Present - Take the Custom Pistol from the Locked Box.","http://www.playstationtrophies.org/images/trophies/1046/842.jpg"],
    ["Ratchet & Clank 2: Going Commando","You can Break a Snow Dan - Blow up the snowman on Siberius","http://www.playstationtrophies.org/images/trophies/1454/FB8.jpg"],
    ["Red Johnson's Chronicles","Hot! Roast chestnuts... - Cut the alarm in less than 20 goes","http://www.playstationtrophies.org/images/trophies/1000/07.jpg"],
    ["Remember Me","Christmas is Over - Finish episode 2","http://www.playstationtrophies.org/images/trophies/1671/F30.jpg"],
    ["Resistance 3","Resistance 3 - Make Santa and his reindeer fly","http://www.playstationtrophies.org/images/trophies/546/10.jpg"],
    ["The Wolf Among Us","A Light Snowfall - Completed Episode 1: \"Faith\"","http://www.playstationtrophies.org/images/trophies/1996/3EE.jpg"],
    ["Toejam & Earl","Even Adults Like Presents - [TJ&E] Snag some goodies from Santa.","http://www.playstationtrophies.org/images/trophies/1758/944.jpg"]
];

var breadList = [
    ["3D Dot Game Heroes","That's a Big Fat Sword! - Maxed out the Giga Sword.","http://www.playstationtrophies.org/images/trophies/365/41.jpg"],
    ["Assassin's Creed IV: Black Flag","Devil Of The Caribbean - Defeat all 4 Legendary Ships.","http://www.playstationtrophies.org/images/trophies/2233/09a.jpg"],
    ["BioShock Infinite","David & Goliath - Killed 20 \"Heavy Hitter\" enemies.","http://www.playstationtrophies.org/images/trophies/700/33C.jpg"],
    ["Borderlands 2","Up High, Down Low - Gave Claptrap a high five","http://www.playstationtrophies.org/images/trophies/1145/39E.jpg"],
    ["Burnout Paradise","Drive 750 miles - Awarded when you reach a total car distance driven of 750 miles","http://www.playstationtrophies.org/images/trophies/1/038.jpg"],
    ["Castle Crashers","Kay Eye Ess Ess - Collect all 4 Princesses' kisses in a multiplayer game.","http://www.playstationtrophies.org/images/trophies/387/01.jpg"],
    ["Dead Space 2","Hard to the Core - Complete the game on Hard Core setting","http://www.playstationtrophies.org/images/trophies/355/47.jpg"],
    ["Demons' Souls","Master Bowman's Trophy - Obtained Best Bow by Spiderstone","http://www.playstationtrophies.org/images/trophies/245/19.jpg"],
    ["Deus Ex: Human Revolution","Balls - Seems you like playing with balls, eh?","http://www.playstationtrophies.org/images/trophies/450/50.jpg"],
    ["Far Cry 3","Never Saw it Coming	- Kill an enemy with a takedown from above from a glider, zipline or parachute (Single Player only).","http://www.playstationtrophies.org/images/trophies/922/E2C.jpg"],
    ["Grand Theft Auto V","Stick Up Kid - GTA Online: Hold up all 20 Stores.","http://www.playstationtrophies.org/images/trophies/687/89c.jpg"],
    ["Hotline Miami","1989 - Kill 1989 enemies.","http://www.playstationtrophies.org/images/trophies/1923/2A0.jpg"],
    ["Lara Croft and The Guardian of Light","Breadwinner - Earn the top score objective in any level","http://www.playstationtrophies.org/images/trophies/433/07.jpg"],
    ["LittleBigPlanet","Friendly - Complete a level with more than one player","http://www.playstationtrophies.org/images/trophies/14/19.jpg"],
    ["Mass Effect 3","Legend - Mission accomplished.","http://www.playstationtrophies.org/images/trophies/845/6CD.jpg"],
    ["Minecraft","Bake Bread - Turn wheat into bread.","http://www.playstationtrophies.org/images/trophies/2376/C6E.jpg"],
    ["Mirror's Edge","Martial artist - Perform a melee hit from a wallrun","http://www.playstationtrophies.org/images/trophies/43/040.jpg"],
    ["Ni No Kuni: Wrath of the White Witch","Humanitarian of the Year - Awarded for running 60 different errands.","http://www.playstationtrophies.org/images/trophies/1399/0EC.jpg"],
    ["Portal 2","Gesticul-8	- Perform all 8 gestures of your own volition in co-op","http://www.playstationtrophies.org/images/trophies/610/38.jpg"],
    ["Ratchet & Clank: A Crack in Time","My Blaster Runs Really, Really Hot - Score 10,000 points on My Blaster Runs Hot.","http://www.playstationtrophies.org/images/trophies/241/18.jpg"],
    ["Rayman Legends","The competitor - Beat your friends' scores in the Challenges 30 times.","http://www.playstationtrophies.org/images/trophies/1526/932.jpg"],
    ["Resident Evil 5","A Friend in Need - Save partner 10 times when HELP is displayed","http://www.playstationtrophies.org/images/trophies/81/028.jpg"],
    ["Sleeping Dogs","Chief Inspector - Complete 100% of all missions, cases, favors, events, jobs and races.","http://www.playstationtrophies.org/images/trophies/1378/64B.jpg"],
    ["Sonic Generations","All Stages Cleared! - Clear Sonic Generations.","http://www.playstationtrophies.org/images/trophies/999/19.jpg"],
    ["South Park: The Stick of Truth","Friends in Strange Places - You befriended both crab people and gnomes.","http://www.playstationtrophies.org/images/trophies/1314/9B2.jpg"],
    ["The Elder Scrolls V: Skyrim","Taking Care of Business - Join the Thieves Guild.","http://www.playstationtrophies.org/images/trophies/826/16.jpg"],
    ["The Last of Us","That's all I got - Survive all of Ellie's jokes.","http://www.playstationtrophies.org/images/trophies/1317/4F4.jpg"],
    ["The Walking Dead","Conversation Killer - Complete chapter 2 of episode 2.","http://www.playstationtrophies.org/images/trophies/1398/C89.jpg"],
    ["Uncharted 3","Combat Leapfrog - Defeat ten enemies in a row, alternating hand-to-hand combat and gunplay","http://www.playstationtrophies.org/images/trophies/373/10.jpg"],
    ["Yakuza 4","Heir to the Powerful - Max out all characters to level 20.","http://www.playstationtrophies.org/images/trophies/586/10.jpg"]
];

var fletchList = [
    ["Assassin's Creed III","Jager Bomb – After becoming fully notorious, kill 10 Jagers before losing your notoriety.","http://www.playstationtrophies.org/images/trophies/1400/A2A.jpg"],
    ["Assassin's Creed IV: Black Flag","Roped In – Perform 5 air assassinations from a swinging rope.","http://www.playstationtrophies.org/images/trophies/1949/F36.jpg"],
    ["Assassin’s Creed Revelations","Mosh Pit – Have 10 guards poisoned at the same time","http://www.playstationtrophies.org/images/trophies/918/42.jpg"],
    ["Alien vs Predator","One Ugly Mother – Complete Predator Campaign on Nightmare difficulty setting","http://www.playstationtrophies.org/images/trophies/323/30.jpg"],
    ["Batman: Arkham City","Pay Your Respects – A moment of remembrance ","http://www.playstationtrophies.org/images/trophies/398/45.jpg"],
    ["Borderlands","My Brother Is An Italian Plumber – Killed an enemy plumber-style","http://www.playstationtrophies.org/images/trophies/39/06.jpg"],
    ["Darksiders","River of Blood – Shed 3000 gallons of demon blood.","http://www.playstationtrophies.org/images/trophies/276/33.jpg"],
    ["Far Cry 3: Blood Dragon","The Only True Stopper – Headshot every type of enemy","http://www.playstationtrophies.org/images/trophies/2000/739.jpg"],
    ["Far Cry 3","Toxophilite - Kill a target from 70m or more with the bow (Single Player only).","http://www.playstationtrophies.org/images/trophies/922/124.jpg"],
    ["Grand Theft Auto V","Red Mist – Complete all rampages ","http://www.playstationtrophies.org/images/trophies/687/f0c.jpg"],
    ["God of War III","Bloody Hell – Cover Kratos in 500 buckets of blood by killing the enemies","http://www.playstationtrophies.org/images/trophies/319/001.jpg"],
    ["Guacamelee","Flawless – Defeat an arena without taking any damage","http://www.playstationtrophies.org/images/trophies/1568/409.jpg"],
    ["Hitman Absolution","Whoops – Achieve your first accidental kill","http://www.playstationtrophies.org/images/trophies/678/B77.jpg"],
    ["InFamous 2","I'm As Shocked As You Are – Defeat an enemy or civilian by stepping in water","http://www.playstationtrophies.org/images/trophies/571/44.jpg"],
    ["L.A. Noire","Roscoe and Friends – Kill at least one bad guy with every gun.","http://www.playstationtrophies.org/images/trophies/358/29.jpg"],
    ["LittleBigPlanet 2","Mortal Coil Shuffler Extraordinaire – Accumulate 20 deaths in one story level.","http://www.playstationtrophies.org/images/trophies/533/17.jpg"],
    ["Lollipop Chainsaw","Zed’s Dead Baby, Zed’s Dead – Defeated Zed","http://www.playstationtrophies.org/images/trophies/1134/012.jpg"],
    ["Mafia 2","Out For Justice – Learn what it means to be a Scaletta","http://www.playstationtrophies.org/images/trophies/351/48.jpg"],
    ["Portal 2","Pit Boss – Show that pit who’s boss","http://www.playstationtrophies.org/images/trophies/610/18.jpg"],
    ["Prototype 2","Two For The Price Of One – Simultaneously kill 2 Brawlers using a single Devastator","http://www.playstationtrophies.org/images/trophies/848/FD9.jpg"],
    ["Red Dead Redemption","Dastardly – Place a hogtied woman on the train tracks, and witness her death by train","http://www.playstationtrophies.org/images/trophies/340/30.jpg"],
    ["Saints Row: The Third","Stay Classy Steelport – Kill 25 Gang Members each with “the Penetrator” AND the Fart in a Jar.","http://www.playstationtrophies.org/images/trophies/746/50.jpg"],
    ["Skyrim","Dragon Hunter – Absorb 20 dragon souls","http://www.playstationtrophies.org/images/trophies/826/45.jpg"],
    ["South Park: The Stick of Truth","Stick Saviour – You defeated Princess Kenny and recovered the stick of truth","http://www.playstationtrophies.org/images/trophies/1314/11C.jpg"],
    ["Star Wars: The Force Unleashed II","Poor Bob – Force Grip a Stormtrooper, impale him with a lightsaber, zap him with Force Lightning, then throw him into an object.","http://www.playstationtrophies.org/images/trophies/397/44.jpg"],
    ["The Last Of Us","The Last Of Us – Survivor + - Complete the game on Survivor +","http://www.playstationtrophies.org/images/trophies/1317/767.jpg"],
    ["The Walking Dead: Season 2","Long Way Down – Witnessed a murder.","http://www.playstationtrophies.org/images/trophies/2352/18.jpg"],
    ["Tomb Raider","Predator – Kill 50 enemies with the bow","http://www.playstationtrophies.org/images/trophies/831/EBC.jpg"],
    ["Uncharted 2: Among Thieves","Survivor – Defeat 75 enemies in a row without dying","http://www.playstationtrophies.org/images/trophies/214/14.jpg"],
    ["Uncharted 3: Drake’s Deception","Expert Ninja – Defeat 5 enemies in a row using Stealth attacks","http://www.playstationtrophies.org/images/trophies/373/42.jpg"]
];

var irvineList = [
    ["Back to the Future: The Game","Back In Time - Traveled back in time to rescue Doc.","http://www.playstationtrophies.org/images/trophies/591/02.jpg"],
    ["Bioshock 2","Grand Daddy - Defeated 3 Big Daddies without dying during the fight.","http://www.playstationtrophies.org/images/trophies/309/28.jpg"],
    ["Brink","Not over till the fat lady sings! - Take down an enemy with gunfire while knocked down","http://www.playstationtrophies.org/images/trophies/356/14.jpg"],
    ["Call of Duty Classic","War Hero - Complete the game on Veteran difficulty","http://www.playstationtrophies.org/images/trophies/277/31.jpg"],
    ["Call of Duty: World at War ","For the Motherland - Complete 'Heart of the Reich' on Veteran difficulty. (Solo only)","http://www.playstationtrophies.org/images/trophies/41/014.jpg"],
    ["Dead Rising 2","Zombie Genocide Master - Kill 72,000 zombies","http://www.playstationtrophies.org/images/trophies/325/04.jpg"],
    ["Dead Space","There's Always Peng - Find the Peng Treasure","http://www.playstationtrophies.org/images/trophies/26/047.jpg"],
    ["Duke Nukem Forever","Balls of Steel - Earn a 1,000,000 pinball score in SP","http://www.playstationtrophies.org/images/trophies/730/30.jpg"],
    ["EA Sports UFC","It’s Showtime! - KO an opponent via cage kick","http://www.playstationtrophies.org/images/trophies/2094/b3c.jpg"],
    ["Eat Lead: The Return of Matt Hazard","Pure Energy - Kill 50 enemies with the Energy Pistol. 'Blaster? I hardly know 'er!'","http://www.playstationtrophies.org/images/trophies/93/042.jpg"],
    ["Far Cry 3","Say Hi to the Internet - Find the lost Hollywood star.","http://www.playstationtrophies.org/images/trophies/922/00F.jpg"],
    ["FIFA 14","No Goal For You! - Perform a Diving Header Clearance","http://www.playstationtrophies.org/images/trophies/1854/EA4.jpg"],
    ["FIFA Street","Street Legend - Defeat Messi in a street challenge game","http://www.playstationtrophies.org/images/trophies/1152/396.jpg"],
    ["Guacamelee","That was Hard Mode? - Defeat the game on Hard mode","http://www.playstationtrophies.org/images/trophies/1568/0A3.jpg"],
    ["Hotline Miami","Get A Life - Get A+ on all the chapters","http://www.playstationtrophies.org/images/trophies/1923/CBA.jpg"],
    ["Jak and Daxter: The Precursor Legacy HD (Jak 1 HD)","The Super Orberator - Collect 2000 Precursor Orbs","http://www.playstationtrophies.org/images/trophies/1217/992.jpg"],
    ["Jetpack Joyride","Romeo Alpha Delta - Fly over 5kms","http://www.playstationtrophies.org/images/trophies/1819/C8B.jpg"],
    ["LEGO Harry Potter: Years 1-4","Quiet Please! - Turn the sound and music down to 0 in the options menu whilst in the library","http://www.playstationtrophies.org/images/trophies/331/33.jpg"],
    ["LEGO Marvel Super Heroes","Avengers Assembled - Collect all Avengers characters in the game (Single Player)","http://www.playstationtrophies.org/images/trophies/1875/E0F.jpg"],
    ["LittleBigPlanet 2","Aces in Spades - Ace 10 different Story levels in a row","http://www.playstationtrophies.org/images/trophies/533/09.jpg"],
    ["Mirror's Edge","Aaaand Safe! - String together the following: wallrun, jump, coil (over obstacle), skill roll","http://www.playstationtrophies.org/images/trophies/43/035.jpg"],
    ["NCIS","Hey, I'm a hacker - Complete first database search","http://www.playstationtrophies.org/images/trophies/1253/03.jpg"],
    ["Need for Speed: Most Wanted","Fast Forward - Trigger a speed camera at over 200mph (321.97km/h)","http://www.playstationtrophies.org/images/trophies/1579/EB1.jpg"],
    ["PlayStation All-Stars Battle Royale","Mr. Bubbles - Complete Arcade Mode with Big Daddy","http://www.playstationtrophies.org/images/trophies/1308/CC2.jpg"],
    ["Prison Break","Invisible - Complete every chapter without being seen.","http://www.playstationtrophies.org/images/trophies/403/43.jpg"],
    ["Saints Row IV","Zoo Keeper - Kill 25 Wardens.","http://www.playstationtrophies.org/images/trophies/1971/7E3.jpg"],
    ["Sniper Elite V2","Deadeye - Snipe an enemy through his eye","http://www.playstationtrophies.org/images/trophies/988/360.jpg"],
    ["The Cave","Win-win-win-win-win-win-win - Everyone reached the bottom.","http://www.playstationtrophies.org/images/trophies/1554/EC2.jpg"],
    ["The Saboteur","Trick or Treat - You stealth killed a Nazi General while disguised.","http://www.playstationtrophies.org/images/trophies/298/43.jpg"],
    ["X-Men Origins: Wolverine","Found! - You found a mysterious hatch!","http://www.playstationtrophies.org/images/trophies/113/039.jpg"]
];

var footballList = [
    ["Assassin's Creed II","High Dive - Perform a Leap of Faith from the Top of Florence's Glotto's Campanile.","http://www.playstationtrophies.org/images/trophies/260/41.jpg"],
    ["Anarchy: Rush Hour","Buy all cars - Buy all possible cars.","http://www.playstationtrophies.org/images/trophies/480/33.jpg"],
    ["Burnout Paradise","Complete 10 Freeburn Challenges - Awarded when you complete your 10th Freeburn Challenge","http://www.playstationtrophies.org/images/trophies/1/048.jpg"],
    ["Buzz!: Quiz TV","The Barnard Award Bronze - Score over 1500 points in a singleplayer game","http://www.playstationtrophies.org/images/trophies/103/015.jpg"],
    ["FIFA Street","Online Dominance - Win all 9 online cups","http://www.playstationtrophies.org/images/trophies/1152/97A.jpg"],
    ["Frogger Returns","The Swamp - Frogger has returned home!!!","http://www.playstationtrophies.org/images/trophies/470/353.jpg"],
    ["God of War","I'll Take the Physical Challenge - Complete the Challenge of the Gods","http://www.playstationtrophies.org/images/trophies/263/3.jpg"],
    ["Heavy Rain","Electrified - The Butterfly - Complete the Butterfly Trial successfully","http://www.playstationtrophies.org/images/trophies/321/22.jpg"],
    ["Jak and Daxter: The Precursor Legacy","Hand Over Fish - Catch 200 Pounds of Fish","http://www.playstationtrophies.org/images/trophies/1217/4FA.jpg"],
    ["Jetpack Joyride","Romeo Alpha Delta - Fly over 5kms","http://www.playstationtrophies.org/images/trophies/1872/C96.jpg"],
    ["L.A. Noire","Bulletproof Windshield - Kill the drivers of both MP vehicles in the gun battle at Hughes Aircraft, before they pull up.","http://www.playstationtrophies.org/images/trophies/358/55.jpg"],
    ["Lara Croft and the Guardian of Light","Jump Jump - Jump from Totec's shield while he is jumping","http://www.playstationtrophies.org/images/trophies/433/05.jpg"],
    ["LittleBigPlanet","Booty Master - Collect all the prize bubbles on the story levels","http://www.playstationtrophies.org/images/trophies/14/36.jpg"],
    ["Need for Speed Undercover","First of Many - Win a Ranked Multiplayer event against 7 human players","http://www.playstationtrophies.org/images/trophies/131/07.jpg"],
    ["Ratchet & Clank 2","You're My Hero - Protect all tourists on Planet Todano from the squirrels","http://www.playstationtrophies.org/images/trophies/1454/7F9.jpg"],
    ["Ratchet & Clank 3: Up Your Arsenal","Hit the Motherload - Collect all 101 Sewer Crystals on Aquatos","http://www.playstationtrophies.org/images/trophies/1455/36B.jpg"],
    ["Ratchet & Clank: A Crack in Time","Insomniac - Visit the Insomniac Museum.","http://www.playstationtrophies.org/images/trophies/241/17.jpg"],
    ["Resogun","Denied! - Save a human from Abductor's beam","http://www.playstationtrophies.org/images/trophies/2229/17.jpg"],
    ["Sound Shapes","Death Mode: Mechanica - Complete the Death Mode level.","http://www.playstationtrophies.org/images/trophies/1406/0D2.jpg"],
    ["The Last of Us","Hunter - Complete the Hunter Journey","http://www.playstationtrophies.org/images/trophies/1317/87C.jpg"],
    ["The Walking Dead","What Remains - Complete Episode 5: 'No Time Left'","http://www.playstationtrophies.org/images/trophies/1398/B8D.jpg"],
    ["Tomb Raider Legend","Goooooooooooooooooooal! - Kick the soccer ball against the door of the church in Peru","http://www.playstationtrophies.org/images/trophies/856/07.jpg"],
    ["Tomb Raider Underworld","Master Survivalist - Complete the game on hardest possible settings","http://www.playstationtrophies.org/images/trophies/143/03.jpg"],
    ["Treasures of Montezuma Blitz","Nuclear Blast - Destroy every token present on game board.","http://www.playstationtrophies.org/images/trophies/1567/2E0.jpg"],
    ["Uncharted: Drake's Fortune","Survivor - Kill 50 enemies in a row without dying","http://www.playstationtrophies.org/images/trophies/8/2.jpg"],
    ["Voodoo Dice","Voodoo sorcerer - Complete all the levels in each world by beating the Voodoo time","http://www.playstationtrophies.org/images/trophies/568/03.jpg"],
    ["Wake-up Club","Best Pals - The Wake-up Club has been successful 365 times.","http://www.playstationtrophies.org/images/trophies/1515/BE4.jpg"],
    ["WipEout 2048","Speed Thrills - ELITE PASS any A+ Class Challenge","http://www.playstationtrophies.org/images/trophies/1093/17.jpg"],
    ["WipEout HD","Da Bomb- Destroy all 14 bombs in any Detonator event.","http://www.playstationtrophies.org/images/trophies/21/40.jpg"],
    ["WWE Legends of WrestleMania","Manager - Win using a manager in an Exhibition match","http://www.playstationtrophies.org/images/trophies/88/001.jpg"]
];

var glennList = [
    ["Assassin's Creed II","Fly Swatter – Kick a Guard while using the Flying Machine.","http://www.playstationtrophies.org/images/trophies/260/23.jpg"],
    ["Assassin's Creed III","Jager Bomb – After becoming fully Notorious, kill 10 Jagers before losing your notoriety.","http://www.playstationtrophies.org/images/trophies/1400/A2A.jpg"],
    ["Far Cry 3","Higher Than a Kite – Use your wingsuit to reach the Southern island.","http://www.playstationtrophies.org/images/trophies/922/16E.jpg"],
    ["FIFA 15","Cool Squad Bro – Copy a Squad from the end of an online match","http://www.playstationtrophies.org/images/trophies/2831/891.jpg"],
    ["FIFA Street","Got any Nutmeg? – Panna your first Opponent","http://www.playstationtrophies.org/images/trophies/1152/804.jpg"],
    ["Grand Theft Auto V","Kifflom! – Complete your path to enlightenment... or not.","http://www.playstationtrophies.org/images/trophies/687/05c.jpg"],
    ["GRID 2","SWAGtastic! – You beat the target time in a Vehicle Challenge.","http://www.playstationtrophies.org/images/trophies/1371/8C7.jpg"],
    ["Guacamelee","We built this city on Guac and Roll – Discover Santa Luchita","http://www.playstationtrophies.org/images/trophies/1568/5F0.jpg"],
    ["inFamous","Member of the Mineral Club – Find 50% of the Shards","http://www.playstationtrophies.org/images/trophies/122/1.jpg"],
    ["Iron Man 2","Extra Crispy – Defeat 100 enemies with Iron Man's laser.","http://www.playstationtrophies.org/images/trophies/404/30.jpg"],
    ["James Bond 007: Blood Stone","Free Fall – Throw 5 people off balconies","http://www.playstationtrophies.org/images/trophies/666/18.jpg"],
    ["L.A Noire","Keep A Lid On – Complete a brawl without losing your hat as an LAPD Detective or Investigator.","http://www.playstationtrophies.org/images/trophies/358/37.jpg"],
    ["LittleBigPlanet","Sticky Fingers – Collect 50% of the prize bubbles on the story levels","http://www.playstationtrophies.org/images/trophies/14/13.jpg"],
    ["Mafia II","Get Rich or Die Flyin' – Get all wheels of your car into the air for at least 20 meters and then touch the ground again.","http://www.playstationtrophies.org/images/trophies/351/25.jpg"],
    ["Men in Black: Alien Crisis","Smile for the Camera! – Neuralize 7 humans in Story Mode","http://www.playstationtrophies.org/images/trophies/1220/4FF.jpg"],
    ["Midnight Club: Los Angeles","Streaker – Win 5 races in a row offline.","http://www.playstationtrophies.org/images/trophies/34/001.jpg"],
    ["Motorstorm RC","Ghost Busted – Beat a friend's ghost in a Race or Hot Lap event who currently sits above you in the leaderboards.","http://www.playstationtrophies.org/images/trophies/1301/07.jpg"],
    ["Rayman: Origins","Kung Fu Combo! – Perform a swipe-to-air Kick Combo!","http://www.playstationtrophies.org/images/trophies/1381/31.jpg"],
    ["Red Dead Redemption","Austin Overpowered – Complete Twin Rocks, Pike's Basin, and Gaptooth Breach Hideouts in Single Player.","http://www.playstationtrophies.org/images/trophies/340/13.jpg"],
    ["Shift 2: Unleashed","Nailed It – Track Mastered your first location","http://www.playstationtrophies.org/images/trophies/696/27.jpg"],
    ["Sleeping Dogs","A Slap in the Face – Kill someone with a fish.","http://www.playstationtrophies.org/images/trophies/1378/0EB.jpg"],
    ["Sly 3: Honor Among Thieves","Everyone needs a foxy lady – Carmelita to the rescue again","http://www.playstationtrophies.org/images/trophies/797/18.jpg"],
    ["Split Second","Untouchable – Win a Race event without crashing.","http://www.playstationtrophies.org/images/trophies/393/12.jpg"],
    ["The Sims 3","Graduated – Complete the in-game tutorial.","http://www.playstationtrophies.org/images/trophies/544/03.jpg"],
    ["The Walking Dead","You Fight Like A Dairy Farmer – Complete chapter 7 of episode 2.","http://www.playstationtrophies.org/images/trophies/1398/18C.jpg"],
    ["Thomas Was Alone","Three Amigos – Find both trophy pickups in 'Array'.","http://www.playstationtrophies.org/images/trophies/1947/BB2.jpg"],
    ["Tomb Raider: Legend","Biggest Bang for the Buck – Blow up 2 mercenaries with 1 propane tank while riding the motorcycle","http://www.playstationtrophies.org/images/trophies/856/13.jpg"],
    ["Tomb Raider","Tastes Like Chicken! – Kill and loot 10 small animals (rabbits, chickens, rats).","http://www.playstationtrophies.org/images/trophies/831/CE8.jpg"],
    ["Uncharted 3: Drake's Deception","Pro-Pain – Defeat 10 enemies with propane or acetylene tank explosions","http://www.ps3trophies.org/images/trophies/373/33.jpg"],
    ["Uncharted: Golden Abyss","Touch My Rear – Use the rear touch pad to climb a rope or chain.","http://www.ps3trophies.org/images/trophies/1092/54.jpg"]
];

var germainList = [
    ["3D Dot Game Heroes","And Everyone Lived Happily Ever After! - Cleared the game with the princess restored.","http://www.playstationtrophies.org/images/trophies/365/24.jpg"],
    ["Acceleration of Suguri X-Edition","What's Your Story - Unlock all character story lines on any difficulty.","http://www.playstationtrophies.org/images/trophies/917/13.jpg"],
    ["AKIBA'S TRIP: Undead & Undressed (PS3/PS4/Vita)","Living Embodiment of Her Happiness - Achieved the little sister ending.","http://www.playstationtrophies.org/images/trophies/2956/859.jpg"],
    ["Ar tonelico Qoga: Knell of Ar Ciel","'Nothing, Ma!' - Hit the Panic Button 100 times.","http://www.playstationtrophies.org/images/trophies/931/03.jpg"],
    ["Daytona USA","YOU JUST LOST YOUR... - Find the hidden sign at the dead end in ADVANCED Course of ARCADE MODE.","http://www.playstationtrophies.org/images/trophies/1208/05.jpg"],
    ["Dead or Alive 5 (Vanilla/Plus/Ultimate)","On the Edge of Your Seat - Play Spectator mode.","http://www.playstationtrophies.org/images/trophies/2205/CB0.jpg"],
    ["Disgaea 3: Absence of Justice","ABC's of Hitting - Get hit by ABC Gum.","http://www.playstationtrophies.org/images/trophies/178/1.jpg"],
    ["Disgaea 4: A Promise Unforgotten","Step Back and Watch the Fireworks - Explode ten Prinnies in a row.","http://www.playstationtrophies.org/images/trophies/1024/36.jpg"],
    ["Disgaea D2: A Brighter Darkness","Ooh La Laharl! - Requirement: Pass the Bill to get Girl Laharl. So...you like Laharl as a girl?","http://www.playstationtrophies.org/images/trophies/2312/F13.jpg"],
    ["Fairy Fencer F","The World's Money is Not Enough - Lola joined the party. 'Despite my appearance, I'm actually a fairy.'","http://www.playstationtrophies.org/images/trophies/3066/c2b.jpg"],
    ["Fighting Vipers","Skirt Destroyer - As Candy unequip armor each Arcade stg or break her lower armor after 10 straight wins in Offline VS","http://www.playstationtrophies.org/images/trophies/1825/D00.jpg"],
    ["Final Fantasy X","All Together - All party members come together","http://www.playstationtrophies.org/images/trophies/1184/011.jpg"],
    ["Final Fantasy X-2","Dressed for the Occasion - Change Dresspheres on Yuna, Rikku, and Paine in one battle","http://www.playstationtrophies.org/images/trophies/2480/383.jpg"],
    ["Final Fantasy XIII","Superstar - Earned a 5-star ranking in the battle to determine the world's fate.","http://www.playstationtrophies.org/images/trophies/307/36.jpg"],
    ["Final Fantasy XIII-2","Giant's Fist - Dealt 99,999 damage with a single attack. ","http://www.playstationtrophies.org/images/trophies/890/4C2.jpg"],
    ["Hatsune Miku Project Diva f/F","Art Collection - You earned the title 'Art Collection'!","http://www.playstationtrophies.org/images/trophies/2251/3A4.jpg"],
    ["Hyperdimension Neptunia mk2","Happily Ever After - Viewed the True ending.","http://www.playstationtrophies.org/images/trophies/1393/5AF.jpg"],
    ["Hyperdimension Neptunia Re;Birth1","True Ending - Watched the True Ending","http://www.playstationtrophies.org/images/trophies/3004/27f.jpg"],
    ["Hyperdimension Neptunia Victory","Hot Stuff: Neptune - \"Everyone's Lily Rank is maxed out with me! Wow, it looks like I'm all kinds of popular!\" -Neptune","http://www.playstationtrophies.org/images/trophies/1892/3DE.jpg"],
    ["Last Rebellion","Fine. dood. we're outta here! - Prinny IV Defeated","http://www.playstationtrophies.org/images/trophies/391/02.jpg"],
    ["Resonance of Fate","Tera-Driver - A trophy for loading over a terabit of data from the disc.","http://www.playstationtrophies.org/images/trophies/339/20.jpg"],
    ["Senran Kagura Shinovi Versus","Presentation of Diploma - Completed all stories.","http://www.playstationtrophies.org/images/trophies/1942/705.jpg"],
    ["Sonic The Fighters","A Small Transformation - Turn small by being attacked (ie, by Amy's↓+P, etc) in Arcade Mode or Offline Versus","http://www.playstationtrophies.org/images/trophies/1826/4E7.jpg"],
    ["Soul Calibur II HD Online","Soul Calibur - Acquired Soul Calibur in Weapon Master","http://www.playstationtrophies.org/images/trophies/2190/4D4.jpg"],
    ["SoulCalibur V","Home is Faraway - Story: cleared final episode. ","http://www.playstationtrophies.org/images/trophies/1016/243.jpg"],
    ["Tekken Tag Tournament 2","Behold the Tekken Lord! - You became Tekken Lord in Offline Mode.","http://www.playstationtrophies.org/images/trophies/756/F31.jpg"],
    ["Trinity Universe","Be the Shooting Star - Hit Count in a Fury Chain exceeds 700.","http://www.playstationtrophies.org/images/trophies/536/13.jpg"],
    ["Under Defeat HD: Deluxe Edition","STOCKPILING ARMS - SCORE A SPECIFIC AMOUNT OR HIGHER FOR AMMUNITION CONSERVATION","http://www.playstationtrophies.org/images/trophies/1753/0F0.jpg"],
    ["Virtua Fighter 5: Final Showdown","Ten Tests Complete - Complete ten tests in License Challenge Mode","http://www.playstationtrophies.org/images/trophies/1169/8C6.jpg"],
    ["Ys: Memories of Celceta","Better Man - Defeated Duren in one-on-one combat.","http://www.playstationtrophies.org/images/trophies/2412/738.jpg"]
];

var labartuList = [
    ["Assassin's Creed IV: Black Flag","Hungover - Wake up in a haystack.","http://www.playstationtrophies.org/images/trophies/2233/866.jpg"],
    ["Batman: Arkham Asylum","Freakshow Rodeo - Ride Titan henchman and knock down 10 thugs (any play mode)","http://www.playstationtrophies.org/images/trophies/192/30.jpg"],
    ["Bayonetta","Angel May Cry - Complete half of all Alfheim portals.","http://www.playstationtrophies.org/images/trophies/52/45.jpg"],
    ["Borderlands 2","Well That Was Easy - Completed the mission 'Shoot This Guy in the Face'","http://www.playstationtrophies.org/images/trophies/1145/CCB.jpg"],
    ["Call of Duty: Modern Warfare 2","Look Ma Two Hands - Kill 10 enemies in a row using akimbo weapons in Single Player or Special Ops.","http://www.playstationtrophies.org/images/trophies/240/49.jpg"],
    ["Catherine","I Can Fly! - Jump on a Spring Block 3 times in a row. (Golden Playhouse)","http://www.playstationtrophies.org/images/trophies/1011/32.jpg"],
    ["Darksiders","Who's Counting? - Defeat more angels than Ulthane","http://www.playstationtrophies.org/images/trophies/276/13.jpg"],
    ["Deadpool","HEEEEY YOOOOO GUYYYYYSSSS! - Take no damage on the waterslide","http://www.playstationtrophies.org/images/trophies/1641/F5E.jpg"],
    ["Dead to Rights: Retribution","Scrotality - Perform a Shadow groin takedown","http://www.playstationtrophies.org/images/trophies/376/33.jpg"],
    ["Enslaved: Odyssey to the West","Bad Doggy - Rescue Trip from the Dog in less than 36 seconds.","http://www.playstationtrophies.org/images/trophies/488/22.jpg"],
    ["Far Cry 3: Blood Dragon","Just the Tip	- Kill a Dragon with the Bow","http://www.playstationtrophies.org/images/trophies/2000/AFD.jpg"],
    ["Fuse","Bro Code Violation - Perform a stealth takedown on the Raven soldier at the urinal.","http://www.playstationtrophies.org/images/trophies/1066/D19.jpg"],
    ["God of War II","You Know the Germans Make Good Stuff... - Collect all Uber Chests","http://www.playstationtrophies.org/images/trophies/264/3.jpg"],
    ["Grand Theft Auto V","Out of Your Depth - You're gonna need a bigger boat...","http://www.playstationtrophies.org/images/trophies/687/0bc.jpg"],
    ["Guacamelee!","Delicious - Complete the World's Greatest Enchilada quest","http://www.playstationtrophies.org/images/trophies/1568/DDE.jpg"],
    ["Mass Effect 2","Insanity - Complete the game in the 'Insanity' difficulty level without changing the setting","http://www.playstationtrophies.org/images/trophies/703/28.jpg"],
    ["Mirror's Edge","Sweet goodbye - Triggered the flip-off move","http://www.playstationtrophies.org/images/trophies/43/043.jpg"],
    ["Portal 2","Pit Boss - Show that pit who's boss","http://www.playstationtrophies.org/images/trophies/610/18.jpg"],
    ["Prototype 2","Arcade Action - Karate kick a helicopter.","http://www.playstationtrophies.org/images/trophies/848/D02.jpg"],
    ["Rayman Legends","Bouncing Island - Collect all the lums flying above the bouncing island in 'The Mysterious Inflatable Island'","http://www.playstationtrophies.org/images/trophies/1526/85C.jpg"],
    ["Rayman Origins","Back At You! - You Bubblized a Hunter with his own live missile!","http://www.playstationtrophies.org/images/trophies/651/37.jpg"],
    ["Red Dead Redemption","What About Hand Grenades? - Get a ringer in a game of Horseshoes.","http://www.playstationtrophies.org/images/trophies/340/12.jpg"],
    ["Remember Me","Fuzzy logic - Hit 5 enemies at once with a Logic Bomb while they are stunned by the Sensen DOS","http://www.playstationtrophies.org/images/trophies/1671/118.jpg"],
    ["Resident Evil 5","They're ACTION Figures! - Collect all the figurines.","http://www.playstationtrophies.org/images/trophies/81/027.jpg"],
    ["Sleeping Dogs","A Slap in the Face - Kill someone with a fish.","http://www.playstationtrophies.org/images/trophies/1378/0EB.jpg"],
    ["South Park: The Stick of Truth","Are We Cool? - You found Jesus while playing as a Jew.","http://www.playstationtrophies.org/images/trophies/1314/654.jpg"],
    ["Star Wars: The Force Unleashed","Worst Day-Shift Manager Ever - Kill 12 Stormtroopers as Vader during the Prologue","http://www.playstationtrophies.org/images/trophies/195/48.jpg"],
    ["Tomb Raider","Former Adventurer - Incapacitate 25 enemies with dodge counter.","http://www.playstationtrophies.org/images/trophies/831/B93.jpg"],
    ["Valiant Hearts: The Great War","Good doggy - Pet the dog","http://www.playstationtrophies.org/images/trophies/2756/be9.jpg"],
    ["Watch_Dogs","Sanity Check - Collect all 8 Burner Phones","http://www.playstationtrophies.org/images/trophies/2250/db0.jpg"]
];

var mendelList = [
    ["Assassin's Creed: Revelations","Bully - Find and beat up Duccio","http://www.playstationtrophies.org/images/trophies/918/50.jpg"],
    ["Asura's Wrath","Like a Fish - Consume more alcohol than you should.","http://www.playstationtrophies.org/images/trophies/751/AAB.jpg"],
    ["Batman: Arkham Asylum","Party Pooper - KO all the henchmen celebrating your arrival at the party","http://www.playstationtrophies.org/images/trophies/192/20.jpg"],
    ["Beyond: Two Souls","Uncontrollable - Took every opportunity to be evil with Aiden","http://www.playstationtrophies.org/images/trophies/1585/691.jpg"],
    ["Bioshock","Irony - The player has taken a picture of Sander Cohen's corpse","http://www.playstationtrophies.org/images/trophies/23/46.jpg"],
    ["Castle Crashers","The Traitor - Defeat any boss by playing one of his own minions.","http://www.playstationtrophies.org/images/trophies/387/03.jpg"],
    ["Dead Space: Extraction","Taking Your Time, McNeill? - Admire the view in the crashed shuttle","http://www.playstationtrophies.org/images/trophies/875/204.jpg"],
    ["Dishonored","Manipulator - You made others kill 5 of their own allies","http://www.playstationtrophies.org/images/trophies/1123/48D.jpg"],
    ["Ducktales: Remastered","Score to Settle - Scrooge doesn't take kindly to being swindled by statues","http://www.playstationtrophies.org/images/trophies/1986/573.jpg"],
    ["Fallout 3","Psychotic Prankster - Placed a grenade or mine while pickpocketing","http://www.playstationtrophies.org/images/trophies/70/047.jpg"],
    ["Fallout: New Vegas","The Courier Who Broke The Bank - Got banned from all the Strip's casinos.","http://www.playstationtrophies.org/images/trophies/343/30.jpg"],
    ["Grand Theft Auto V","Altruist Acolyte - Deliver an unsuspecting victim to the Altruist Cult.","http://www.playstationtrophies.org/images/trophies/687/864.jpg"],
    ["HEAVY RAIN","Perfect Crime - Clean Manfred's shop of evidence + Let Lauren, Hassan and Kramer die + Kill Madison and Jayden + Origami Killer free","http://www.playstationtrophies.org/images/trophies/321/56.jpg"],
    ["Hitman: Absolution","Whoops - Achieve your first accident kill","http://www.playstationtrophies.org/images/trophies/678/B77.jpg"],
    ["Hotline Miami","Smell Something Burning - Kill the crapping gangster with a fireaxe","http://www.playstationtrophies.org/images/trophies/1923/23B.jpg"],
    ["InFamous 2","Discerning Taste - Take down a street performer who is imitating a statue.","http://www.playstationtrophies.org/images/trophies/571/43.jpg"],
    ["LittleBigPlanet 2","Turbo Slapper - Slap more than one player at once","http://www.playstationtrophies.org/images/trophies/533/29.jpg"],
    ["Lollipop Chainsaw","I Swear! I Did It By Mistake! - Peeped under Juliet's skirt once.","http://www.playstationtrophies.org/images/trophies/1134/016.jpg"],
    ["Metal Gear Solid 2","Sexting - Send Otacon a picture of the marine with no pants","http://www.playstationtrophies.org/images/trophies/1053/07.jpg"],
    ["Mirror's Edge","Sweet goodbye - Triggered the flip-off move","http://www.playstationtrophies.org/images/trophies/43/043.jpg"],
    ["Monkey Island 2: LeChuck's Revenge","Five Minutes Later... - Allow Guybrush to die","http://www.playstationtrophies.org/images/trophies/523/09.jpg"],
    ["Need for Speed: Most Wanted","Mauled - Wreck 10 cops in a single pursuit in the Ford F-150 SVT Raptor","http://www.playstationtrophies.org/images/trophies/1579/7B0.jpg"],
    ["Portal 2","You Made Your Point - Refuse to solve the first test in Chapter 8","http://www.playstationtrophies.org/images/trophies/610/29.jpg"],
    ["Red Dead Redemption","Dastardly - Place a hogtied woman on the train tracks, and witness her death by train.","http://www.playstationtrophies.org/images/trophies/340/30.jpg"],
    ["Rocketbirds","For What Reason? - Launch the silo missile","http://www.playstationtrophies.org/images/trophies/1192/23.jpg"],
    ["South Park: The Stick of Truth","Acceptance - You accepted your fate and chose the name Douchebag yourself.","http://www.playstationtrophies.org/images/trophies/1314/18F.jpg"],
    ["Spec Ops: The Line","Unfriendly Fire - Save a bullet","http://www.playstationtrophies.org/images/trophies/613/7FC.jpg"],
    ["The Cave","Such Bad Children - Broke things","http://www.playstationtrophies.org/images/trophies/1554/552.jpg"],
    ["The Elder Scrolls V: Skyrim","Master Criminal - Bounty of 1000 gold in all nine holds","http://www.playstationtrophies.org/images/trophies/826/36.jpg"],
    ["Uncharted 3: Drake's Deception","He's Gonna Need a Sturgeon - Hit three enemies with fish in the market","http://www.playstationtrophies.org/images/trophies/373/47.jpg"]
];

var olsenList = [
    ["Alpha Protocol","One With The Shadows - Complete 3 missions with less than 5 kills and with no enemies alerted to your presence.","http://www.playstationtrophies.org/images/trophies/51/46.jpg"],
    ["Assassin's Creed III: Liberation","Umbrella - Kill 25 enemies with the Parasol Gun","http://www.playstationtrophies.org/images/trophies/1155/1D2.jpg"],
    ["Batman: Arkham City","Contract Terminated - Stop the contract operative","http://www.playstationtrophies.org/images/trophies/398/17.jpg"],
    ["Batman: Arkham Origins","Gotham Protector - Master the Gotham Protector Dark Knight track","http://www.playstationtrophies.org/images/trophies/2009/A46.jpg"],
    ["Battlefield 3","Army of Two - Completed all co-op missions on Hard","http://www.playstationtrophies.org/images/trophies/883/29.jpg"],
    ["Battlefield 4",".45 old school - Perform 45 kills with the M1911 Handgun in Multiplayer","http://www.playstationtrophies.org/images/trophies/1640/B30.jpg"],
    ["Bioshock Infinite","Heartbreaker - Killed a Handyman by only shooting his heart.","http://www.playstationtrophies.org/images/trophies/700/1E4.jpg"],
    ["Crysis","Cool In A Crysis - Complete the game on Hard or Delta difficulty","http://www.playstationtrophies.org/images/trophies/1183/23.jpg"],
    ["Dead Nation","Aim For The Head - Perform 500 Headshots","http://www.playstationtrophies.org/images/trophies/592/24.jpg"],
    ["Dead Space 2","Epic Dismemberment - Dismember 2,500 Necromorph Limbs (single player only)","http://www.playstationtrophies.org/images/trophies/355/26.jpg"],
    ["Diablo III","Greed over Need - Kill 100 Treasure Goblins.","http://www.playstationtrophies.org/images/trophies/1935/045.jpg"],
    ["Doom Classic Complete","Knuckle Sammich - Kill a CyberDemon with your fists in singleplayer.","http://www.playstationtrophies.org/images/trophies/1814/211.jpg"],
    ["Doom 3","Ready for Action! - Get the BFG-9000 from Security Chief's office in DOOM 3","http://www.playstationtrophies.org/images/trophies/1561/14A.jpg"],
    ["Fallout 3","You Gotta Shoot 'Em in the Head - Completed 'You Gotta Shoot 'Em in the Head'","http://www.playstationtrophies.org/images/trophies/70/026.jpg"],
    ["Fallout: New Vegas","Master of the Arsenal - Caused 10,000 damage with Gun Runners' Arsenal (GRA) Weapons.","http://www.playstationtrophies.org/images/trophies/343/73.jpg"],
    ["Far Cry 3: Blood Dragon","The Only True Stopper - Headshot Every Type of Enemy","http://www.playstationtrophies.org/images/trophies/2000/739.jpg"],
    ["Injustice: Gods Among Us","Perfect Aim - Win a match as Deathstroke without missing a shot (minimum 12 shots)","http://www.playstationtrophies.org/images/trophies/1572/41A.jpg"],
    ["Killzone 3","Eagle Eye - Shot and killed 6 Helghast using the Sniper Rifle without reloading or switching weapons","http://www.playstationtrophies.org/images/trophies/430/36.jpg"],
    ["Killzone: Mercenary","Full Deck - Collect a full deck of Valour cards","http://www.playstationtrophies.org/images/trophies/1675/EE7.jpg"],
    ["LA Noire","Roscoe And Friends - Kill at least one bad guy with every gun.","http://www.playstationtrophies.org/images/trophies/358/29.jpg"],
    ["Mafia II","Hairdresser - Kill 5 enemies in rapid succession with a headshot.","http://www.playstationtrophies.org/images/trophies/351/31.jpg"],
    ["Mass Effect","Extreme Power Gamer - Reach 60th level with one character","http://www.playstationtrophies.org/images/trophies/1743/DB0.jpg"],
    ["Mass Effect 2","No One Left Behind - Keep your team alive through the suicide mission","http://www.playstationtrophies.org/images/trophies/703/29.jpg"],
    ["Mass Effect 3","Veteran - Kill 5,000 enemies.","http://www.playstationtrophies.org/images/trophies/845/37F.jpg"],
    ["Portal 2","No Hard Feelings - Save a turret from redemption","http://www.playstationtrophies.org/images/trophies/610/24.jpg"],
    ["Red Dead Redemption","Bearly Legal - Kill and skin 18 grizzly bears.","http://www.playstationtrophies.org/images/trophies/340/23.jpg"],
    ["Resistance 3","Feeling Lucky, Punk - Detonate multiple Magnum rounds to kill 2+ enemies at once, 5 times","http://www.playstationtrophies.org/images/trophies/546/44.jpg"],
    ["Starhawk","Deadeye - With the LR-3 Railgun, kill an enemy from more than 2,500 feet away.","http://www.playstationtrophies.org/images/trophies/421/3B2.jpg"],
    ["Unreal Tournament III","Fear the Reaper - Defeat Akasha and complete the campaign in Insane.","http://www.playstationtrophies.org/images/trophies/108/009.jpg"],
    ["XCOM: Enemy Unknown","Shooting Stars - Shoot down 40 UFOs.","http://www.playstationtrophies.org/images/trophies/1350/415.jpg"]
];

var phantomList = [
    ["Army of Two: The Devil's Cartel","Army of TWO - Perform 250 Flank, Surprise and/or Tag Team kills","http://www.playstationtrophies.org/images/trophies/1656/490.jpg"],
    ["Assassin's Creed II","Vitruvian Man - Unlock all 20 pieces of Subject 16's video","http://www.playstationtrophies.org/images/trophies/260/21.jpg"],
    ["Bioshock Infinite","Dress for Success - Equipped a piece of Gear in all four slots","http://www.playstationtrophies.org/images/trophies/700/994.jpg"],
    ["Borderlands 2","Phased and Confused - Phaselocked 100 enemies","http://www.playstationtrophies.org/images/trophies/1145/390.jpg"],
    ["Brink","It's a Trap! - Take down an enemy with a Satchel Charge","http://www.playstationtrophies.org/images/trophies/356/30.jpg"],
    ["Dead Nation","Survivor - Complete a mission without dying","http://www.playstationtrophies.org/images/trophies/592/19.jpg"],
    ["Dead Space 2","Vacuum Cleaner - Decompress 20 Necromorphs without getting sucked out yourself","http://www.playstationtrophies.org/images/trophies/355/20.jpg"],
    ["Fallout 3","Data Miner - Hacked 50 terminals","http://www.playstationtrophies.org/images/trophies/70/044.jpg"],
    ["Fuse","Bro Code Violation - Perform a stealth takedown on the Raven soldier at the urinal","http://www.playstationtrophies.org/images/trophies/1066/D19.jpg"],
    ["Grand Theft Auto V","Kifflom! - Complete your path to enlightenment... or not","http://www.playstationtrophies.org/images/trophies/687/05c.jpg"],
    ["Heavy Rain","Four Heroes - Complete the story with four characters alive","http://www.playstationtrophies.org/images/trophies/321/52.jpg"],
    ["Mass Effect 2","The Cure - Gain the loyalty of the Professor","http://www.playstationtrophies.org/images/trophies/703/18.jpg"],
    ["Mass Effect 3","Long Service Medal - Complete Mass Effect 3 twice, or once with a Mass Effect 2 import","http://www.playstationtrophies.org/images/trophies/845/C12.jpg"],
    ["Medal of Honor: Frontline","Trigger Happy - Fire 5,000 shots","http://www.playstationtrophies.org/images/trophies/772/29.jpg"],
    ["Oddworld: Stranger's Wrath HD","Hidden What?! - Find the Black Market","http://www.playstationtrophies.org/images/trophies/731/54A.jpg"],
    ["Portal 2","The Part Where He Kills You - This is that part","http://www.playstationtrophies.org/images/trophies/610/14.jpg"],
    ["Rage","Decapthon - Get 10 Headshot kills with the Wingstick","http://www.playstationtrophies.org/images/trophies/354/11.jpg"],
    ["Ratchet and Clank 3: Up Your Arsenal","Secret Agent Clank - Find the Clank Trophy","http://www.playstationtrophies.org/images/trophies/1455/AA0.jpg"],
    ["Red Dead Redemption","No Dice - Complete a game of Liar's Dice without losing a single die","http://www.playstationtrophies.org/images/trophies/340/11.jpg"],
    ["Resident Evil 5","Egg on Your Face - Defeat a Majini with a rotten egg","http://www.playstationtrophies.org/images/trophies/81/048.jpg"],
    ["Resistance 3","Access Denied - Absorb 1,000 damage with Auger Shields","http://www.playstationtrophies.org/images/trophies/546/56.jpg"],
    ["Rocketbirds: Hardboiled Chicken","Laser Assist - Kill an enemy by knocking him into a laser door","http://www.playstationtrophies.org/images/trophies/1192/26.jpg"],
    ["Sleeping Dogs","Karaoke Superstar - Achieving 90% and above for all songs at the Karaoke Bars in HK","http://www.playstationtrophies.org/images/trophies/1378/58B.jpg"],
    ["Sniper Elite V2","Potato Masher - Kill 100 enemies with explosives","http://www.playstationtrophies.org/images/trophies/988/50A.jpg"],
    ["Sound Shapes","Death Mode: Touch the People - Complete the Death Mode level","http://www.playstationtrophies.org/images/trophies/1076/B5D.jpg"],
    ["The Saboteur","Top o' the World - You climbed to the top of the Eiffel Tower","http://www.playstationtrophies.org/images/trophies/298/18.jpg"],
    ["The Walking Dead","What Remains - Complete Episode 5: 'No Time Left'","http://www.playstationtrophies.org/images/trophies/1398/B8D.jpg"],
    ["WipEout HD","Beat Zico - Equal or beat the lap time of 30.82 seconds on Anulpha Pass (Forward), Speed Lap, Venom using the Piranha","http://www.playstationtrophies.org/images/trophies/21/025.jpg"],
    ["X-Men Origins: Wolverine","The Cake - You found the cake, yummy!","http://www.playstationtrophies.org/images/trophies/113/048.jpg"],
    ["X-Men: Destiny","U Mad, Bro? - Defeat 30 U-Men in the Secret Lab","http://www.playstationtrophies.org/images/trophies/770/47.jpg"]
];

var savList = [
    ["Assassins Creed II","Show your Colors - Wear the Auditore cape in each city.","http://www.playstationtrophies.org/images/trophies/260/38.jpg"],
    ["Batman Arkham Asylum","Flawless Freeflow Fighter - Complete one combat challenge without taking damage","http://www.playstationtrophies.org/images/trophies/192/38.jpg"],
    ["Beyond: Two Souls","Houdini - Got arrested three times and escaped each time.","http://www.playstationtrophies.org/images/trophies/1585/353.jpg"],
    ["Borderlands","My Brother is an Italian Plumber - Killed an enemy plumber-style","http://www.playstationtrophies.org/images/trophies/39/06.jpg"],
    ["Dante’s Inferno","Poetry in Motion - Perform a 666 hit combo","http://www.playstationtrophies.org/images/trophies/322/28.jpg"],
    ["Dead Space","Don't get cocky, kid - Survive the ADS Canon with over 50% Shield strength remaining","http://www.playstationtrophies.org/images/trophies/26/032.jpg"],
    ["Enslaved Odyssey to the West","Tech Curator - Collect all Tech Orbs","http://www.playstationtrophies.org/images/trophies/488/49.jpg"],
    ["GTA IV","Gobble Gobble - You got a turkey in 10-pin bowling.","http://www.playstationtrophies.org/images/trophies/33/008.jpg"],
    ["GTA V","Close Shave - Complete all Under the Bridge and Knife Flight challenges.","http://www.playstationtrophies.org/images/trophies/687/883.jpg"],
    ["Heavy Rain","All Endings - See all endings","http://www.playstationtrophies.org/images/trophies/321/57.jpg"],
    ["Hitman 2","All Firearms collected - All Firearms collected and displayed in Hideout","http://www.playstationtrophies.org/images/trophies/1770/410.jpg"],
    ["James Bond 007: Blood Stone","No Claims Bonus - Drive to the bridge in the epilogue level without hitting any other vehicles","http://www.playstationtrophies.org/images/trophies/666/36.jpg"],
    ["Just Cause II","Trying Everything Once - Drive all 104 vehicles.","http://www.playstationtrophies.org/images/trophies/329/01.jpg"],
    ["LA Noire","Roscoe And Friends - Kill at least one bad guy with every gun.","http://www.playstationtrophies.org/images/trophies/358/29.jpg"],
    ["Mafia II","One Careful Owner - Travel a total of 50 miles in one vehicle.","http://www.playstationtrophies.org/images/trophies/351/27.jpg"],
    ["Mass Effect 2","No One Left Behind - Keep your team alive through the suicide mission","http://www.playstationtrophies.org/images/trophies/703/29.jpg"],
    ["Metal Gear Solid 2","Johnny on the Spot - Hear Johnny's bowel noises in two locations","http://www.playstationtrophies.org/images/trophies/1053/16.jpg"],
    ["Mirrors Edge","Test of Faith - Complete the game without shooting an enemy","http://www.playstationtrophies.org/images/trophies/43/039.jpg"],
    ["Portal 2","Schrodinger's Catch - Catch a blue-painted box before it touches the ground","http://www.playstationtrophies.org/images/trophies/610/25.jpg"],
    ["Prince of Persia","Light Seeds Master - Collect 1001 Light Seeds.","http://www.playstationtrophies.org/images/trophies/59/036.jpg"],
    ["Red Dead Redemption","Dastardly - Place a hogtied woman on the train tracks, and witness her death by train.","http://www.playstationtrophies.org/images/trophies/340/30.jpg"],
    ["Resident Evil 5","Lead Aspirin - Defeat a Majini with a headshot while it's jumping.","http://www.playstationtrophies.org/images/trophies/81/037.jpg"],
    ["Sleeping Dogs","Mr. Nice Guy - Complete all Favors","http://www.playstationtrophies.org/images/trophies/1378/573.jpg"],
    ["Sniper Elite V2","Get Off the ground - Kill everyone in the convoy from ground level, except for Kreidl","http://www.playstationtrophies.org/images/trophies/988/10E.jpg"],
    ["The Elder Scrolls V: Skyrim","Master Criminal - Bounty of 1000 gold in all nine holds","http://www.playstationtrophies.org/images/trophies/826/36.jpg"],
    ["The Godfather II","Accept This As A Gift - Earn one of each favour.","http://www.playstationtrophies.org/images/trophies/50/040.jpg"],
    ["The Last of Us","That's all I got - Survive all of Ellie's jokes","http://www.playstationtrophies.org/images/trophies/1317/4F4.jpg"],
    ["The Saboteur","Guerilla Warfare - You completed 425 ambient freeplay in the countryside","http://www.playstationtrophies.org/images/trophies/298/39.jpg"],
    ["Tomb Raider","Chatterbox - Complete all conversations with the Endurance crew.","http://www.playstationtrophies.org/images/trophies/831/83D.jpg"],
    ["Uncharted II: Among Thieves","Steel Fist Expert - Defeat ten enemies in a row with a single punch, after softening them up with gunfire","http://www.playstationtrophies.org/images/trophies/214/41.jpg"]
];

var shadowList = [
    ["3D Dot Game Heroes","Flawless Hero! - Cleared the game without dying.","http://www.playstationtrophies.org/images/trophies/573/E93.jpg"],
    ["Alpha Protocol","Antisocial - Get 3 people to hate you (who must all hate you at the same time).","http://www.playstationtrophies.org/images/trophies/51/38.jpg"],
    ["Borderlands","12 Days of Pandora - Mastered the technology of Pandora.","http://www.playstationtrophies.org/images/trophies/39/09.jpg"],
    ["Burnout Paradise","Smash 60 Burnout Billboards - Awarded when you smash through your 60th pristine Burnout Billboard","http://www.playstationtrophies.org/images/trophies/1/018.jpg"],
    ["Catherine","Text Junkie - Reply to at least 20 text messages by the end of the final day.","http://www.playstationtrophies.org/images/trophies/1011/27.jpg"],
    ["Dark Souls","Rite of Kindling - Acquire the Rite of Kindling.","http://www.playstationtrophies.org/images/trophies/755/32.jpg"],
    ["Dead Space 2","Looking Good - Purchase the Advanced Suit.","http://www.playstationtrophies.org/images/trophies/355/27.jpg"],
    ["Deus Ex: Human Revolution","Balls - Seems you like playing with balls, eh?","http://www.playstationtrophies.org/images/trophies/450/50.jpg"],
    ["Dynasty Warriors 7","OK, you can pursue Lu Bu - Defeated Lu Bu for the first time.","http://www.playstationtrophies.org/images/trophies/792/50.jpg"],
    ["Fallout 3","The Bigger They Are... - Kill all the Super Mutant Behemoths","http://www.playstationtrophies.org/images/trophies/70/048.jpg"],
    ["FIFA 12","Procrastinator - Sign a player on Deadline Day in the transfer window in Career Mode.","http://www.playstationtrophies.org/images/trophies/972/38.jpg"],
    ["Grand Theft Auto IV","One Man Army - You survived a 6 star wanted level for a full 5 minutes.","http://www.playstationtrophies.org/images/trophies/33/015.jpg"],
    ["Guacamelee","Boom-Shack-Calaca - Defeat Calaca","http://www.playstationtrophies.org/images/trophies/1568/972.jpg"],
    ["Jet Set Radio","The gangs all here - Unlock all characters","http://www.playstationtrophies.org/images/trophies/1411/062.jpg"],
    ["Kingdoms of Amalur: Reckoning","Would You Like Fries with that? - Landed 100 complete attack chains.","http://www.playstationtrophies.org/images/trophies/669/DAA.jpg"],
    ["Metro: Last Light","Tortoise - Make 10 Spiders flip belly-up.","http://www.playstationtrophies.org/images/trophies/1046/C9D.jpg"],
    ["NIER","The Sheep Whisperer - You killed 100 sheep","http://www.playstationtrophies.org/images/trophies/379/30.jpg"],
    ["Pinball Arcade","Black Hole High 5 - Achieve a top 5 local high score on Black Hole&trade;","http://www.playstationtrophies.org/images/trophies/1496/EDC.jpg"],
    ["Rayman Origins","Dr. Lividstone, I presume? - You found ALL hidden cages.","http://www.playstationtrophies.org/images/trophies/651/10.jpg"],
    ["Red Dead Redemption","Fightin' Around the World - Knock someone out in melee in every saloon in the game in Single Player.","http://www.playstationtrophies.org/images/trophies/340/16.jpg"],
    ["Shadows of the Damned","That's So Hot! - Defeat 20 enemies with the HOTBONER","http://www.playstationtrophies.org/images/trophies/748/38.jpg"],
    ["Sleeping Dogs","A Slap in the Face - Kill someone with a fish.","http://www.playstationtrophies.org/images/trophies/1378/0EB.jpg"],
    ["Spec Ops: The Line","A Line, Crossed - Choose vengeance.","http://www.playstationtrophies.org/images/trophies/613/D99.jpg"],
    ["Star Ocean: The Last Hope International","Rookie Battler - Obtain 15% of all battle trophies.","http://www.playstationtrophies.org/images/trophies/328/02.jpg"],
    ["The Walking Dead","Too Much Salt Will Kill You - Complete chapter 5 of episode 2.","http://www.playstationtrophies.org/images/trophies/1398/2C4.jpg"],
    ["Uncharted 2: Among Thieves","Master Ninja - Defeat 50 enemies with stealth attacks.","http://www.playstationtrophies.org/images/trophies/214/40.jpg"],
    ["Virtue's Last Reward","Fire and Ice - Saw the end. Or maybe the beginning?","http://www.playstationtrophies.org/images/trophies/1773/701.jpg"],
    ["Wipeout HD","Thanks for the Memory - Win a Campaign, Racebox or Online race using each HUD style variation.","http://www.playstationtrophies.org/images/trophies/21/016.jpg"],
    ["XCOM: Enemy Unknown","As a Scalpel - Earn the \"Excellent\" rating in every performance category on a terror mission.","http://www.playstationtrophies.org/images/trophies/1350/817.jpg"],
    ["Yakuza 4","Indomitable - Clear Normal Mode without reverting to Easy Mode.","http://www.playstationtrophies.org/images/trophies/586/11.jpg"]
];

var terminatorList = [
    ["Bioshock","Completed Welcome - The player has successfully completed the Welcome To Rapture Level","http://www.playstationtrophies.org/images/trophies/23/1.jpg"],
    ["Duke Nukem Forever","Duke Angry, Duke Smash! - Kill 15 aliens with melee attacks while on steroids","http://www.playstationtrophies.org/images/trophies/730/14.jpg"],
    ["Port Royale 3: Pirates and Merchants","Power Drinker - Visit all 60 taverns","http://www.playstationtrophies.org/images/trophies/1703/B0D.jpg"],
    ["Red Faction: Armageddon","Cheater! - Buy a Cheat.","http://www.playstationtrophies.org/images/trophies/583/30.jpg"],
    ["Killer is Dead","Suck Like a Leech - Killed an enemy using the \"Burst Rush.\"","http://www.playstationtrophies.org/images/trophies/1492/982.jpg"],
    ["Dead Space 2","Lightspeed de Milo - Dismember the Lightspeed Boy Statue","http://www.playstationtrophies.org/images/trophies/355/32.jpg"],
    ["Far Cry 3: Blood Dragon","Murder Nature - Kill all the Animal Types","http://www.playstationtrophies.org/images/trophies/2000/8B7.jpg"],
    ["Back to the Future: The Game","One Bad Apple - Collect every Demerit in the game.","http://www.playstationtrophies.org/images/trophies/1245/32.jpg"],
    ["Aliens: Colonial Marines","Mostly Come at Night... - Find Newt's doll","http://www.playstationtrophies.org/images/trophies/736/FD6.jpg"],
    ["Sega Mega Drive Ultimate Collection / Sonic's Ultimate Genesis Collection","Complete Chaos - Sonic The Hedgehog: Obtain a Chaos Emerald","http://www.playstationtrophies.org/images/trophies/173/22.jpg"],
    ["Heavy Rain","Fugitive - Manage to escape Blake in the subway station","http://www.playstationtrophies.org/images/trophies/321/27.jpg"],
    ["The Elder Scrolls V: Skyrim","Wanted - Escape from jail","http://www.playstationtrophies.org/images/trophies/826/33.jpg"],
    ["Monkey Island 2 Special Edition: LeChuck's Revenge","Call 911 - Call the LucasArts helpdesk when walking through the jungle on Dinky Island","http://www.playstationtrophies.org/images/trophies/523/12.jpg"],
    ["Plants vs. Zombies","Close Shave - Survive the zombie onslaught after all lawnmowers have been used","http://www.playstationtrophies.org/images/trophies/901/10.jpg"],
    ["Fallout 3","The Wasteland Survival Guide - Completed 'The Wasteland Survival Guide'","http://www.playstationtrophies.org/images/trophies/70/016.jpg"],
    ["inFamous","Clean Up Your Act - Defeat Sasha","http://www.playstationtrophies.org/images/trophies/122/2.jpg"],
    ["Borderlands 2","Always Improving - Reached level 25","http://www.playstationtrophies.org/images/trophies/1145/9ED.jpg"],
    ["Resident Evil 5","Who Do You Trust? - Build up a certain level of trust with your partner.","http://www.playstationtrophies.org/images/trophies/81/050.jpg"],
    ["Mass Effect 2","Paramour - Successfully pursue a relationship with a teammate","http://www.playstationtrophies.org/images/trophies/703/31.jpg"],
    ["Minecraft","Leader Of The Pack - Befriend five wolves.","http://www.playstationtrophies.org/images/trophies/2376/2EE.jpg"],
    ["Lollipop Chainsaw","Perfect Body - Completely level up Juliet.","http://www.playstationtrophies.org/images/trophies/1134/1C7.jpg"],
    ["Bioshock Infinite","Mind Over Matter - Killed 20 enemies using Possessed machines.","http://www.playstationtrophies.org/images/trophies/700/BD3.jpg"],
    ["Earth Defense Force: Insect Armageddon","Who Ravages the Ravagers? - Kill 25000 Enemies. Master killer","http://www.playstationtrophies.org/images/trophies/754/25.jpg"],
    ["Bioshock 2","Big Brass Balls - Finished the game without using Vita-Chambers.","http://www.playstationtrophies.org/images/trophies/309/36.jpg"],
    ["The Walking Dead: Season Two","Eye of the Storm - Completed Episode 3: \"In Harm’s Way\"","http://www.playstationtrophies.org/images/trophies/2352/24.jpg"],
    ["The Secret of Monkey Island: Special Edition","Guybrush Kicks Butt - Complete Last Part: Guybrush Kicks Butt.","http://www.playstationtrophies.org/images/trophies/439/04.jpg"],
    ["Terminator Salvation","For the Resistance - Complete Chapter 9 - For the Resistance on any difficulty","http://www.playstationtrophies.org/images/trophies/112/009.jpg"],
    ["Dishonored","Poetic Justice - You neutralized all key targets using indirect means","http://www.playstationtrophies.org/images/trophies/1123/EAD.jpg"],
    ["The Walking Dead: Season 1","Everything's Going to be Okay - Complete Episode 1: \"A New Day\"","http://www.playstationtrophies.org/images/trophies/1398/3CE.jpg"],
    ["Catherine","Dreams Come True - View all of the endings.","http://www.playstationtrophies.org/images/trophies/1011/19.jpg"]
];

var techList = [
    ["Alex Kidd in Miracle World","Good Vibrations - Freeze in fear from breaking a Skull Block.","http://www.playstationtrophies.org/images/trophies/1549/16B.jpg"],
    ["Batman: Arkham Asylum","Rope-a-dope-a-dope - String up one henchman and drop him to surprise a second (any play mode).","http://www.playstationtrophies.org/images/trophies/192/24.jpg"],
    ["Bioshock","Seriously Good at This - The player has completed the game on the Hard difficulty setting","http://www.playstationtrophies.org/images/trophies/23/43.jpg"],
    ["Captain America: Super Soldier","Pow, Right in the Kisser - Performed 50 Crippling Strikes","http://www.playstationtrophies.org/images/trophies/769/23D.jpg"],
    ["Catherine","The Golden Child - Earn Gold Prizes on all Hard difficulty stages.","http://www.playstationtrophies.org/images/trophies/1011/47.jpg"],
    ["Dead Space 2","Peek a Boo! - Kill a Stalker with the Seeker Rifle while in Zoom Mode","http://www.playstationtrophies.org/images/trophies/355/42.jpg"],
    ["Demon's Souls","Master Slasher's Trophy - Obtained Best Weapon by Bladestone","http://www.playstationtrophies.org/images/trophies/150/18.jpg"],
    ["Dragon Fantasy: Book I","Well Educated - Read 30 Different Books in Ogden's Story.","http://www.playstationtrophies.org/images/trophies/2014/B8D.jpg"],
    ["Duke Nukem Forever","Full Body Tourettes - Get knocked down 10 times","http://www.playstationtrophies.org/images/trophies/730/17.jpg"],
    ["Fallout: New Vegas","Love the Bomb - Cause 10,000 damage with Explosives.","http://www.playstationtrophies.org/images/trophies/343/14.jpg"],
    ["Final Fantasy XIII-2","Choco-boco-holic - Spent a fortune at shops.","http://www.playstationtrophies.org/images/trophies/890/6DE.jpg"],
    ["God of War III","Vengeance Complete - Beat the game","http://www.playstationtrophies.org/images/trophies/319/003.jpg"],
    ["Gravity Rush","Frequent Flyer - Landed 10 gravity kicks without landing or taking damage.","http://www.playstationtrophies.org/images/trophies/1392/28.jpg"],
    ["Hatsune Miku: Project Diva F","Skilled Player - You earned the title \"Skilled Player\"!","http://www.playstationtrophies.org/images/trophies/2251/398.jpg"],
    ["Iron Man 2","Anger Management - Destroy most of the structures in Shatalov's base.","http://www.playstationtrophies.org/images/trophies/404/15.jpg"],
    ["Mass Effect 3","Long Service Medal - Complete Mass Effect 3 twice, or once with a Mass Effect 2 import.","http://www.playstationtrophies.org/images/trophies/845/C12.jpg"],
    ["NASCAR Unleashed","Rocketman - Slingshot into 25 ramp jumps","http://www.playstationtrophies.org/images/trophies/1256/19.jpg"],
    ["NCIS","You know I'm awesome - Collect first piece of evidence","http://www.playstationtrophies.org/images/trophies/1253/27.jpg"],
    ["Portal 2","Professor Portal - After completing co-op, complete Calibration Course online with a friend who hasn’t played before","http://www.playstationtrophies.org/images/trophies/610/43.jpg"],
    ["Ratchet & Clank: A Crack in Time","Rude Awakening - Complete Great Clock, Sector One.","http://www.playstationtrophies.org/images/trophies/241/03.jpg"],
    ["Resident Evil 5","Stop, Drop, & Roll - Defeat 3 Majini at once by setting oil canisters on fire.","http://www.playstationtrophies.org/images/trophies/81/043.jpg"],
    ["Sam & Max: The Devil's Playhouse - Episode 3: They Stole Max's Brain Trophies","Tweenage Angst - Have Sammunmak banish every possible object in Act 3","http://www.playstationtrophies.org/images/trophies/633/08.jpg"],
    ["Saw II: Flesh & Blood","Now THAT’S using your head! - Escaped 'The Bullish Man'","http://www.playstationtrophies.org/images/trophies/525/08.jpg"],
    ["Sega Mega Drive Ultimate Collection/Sonic's Ultimate Genesis Collection","Get to the Chopper - Super Thunder Blade: Score over 1,500,000 points in the first level","http://www.playstationtrophies.org/images/trophies/85/025.jpg"],
    ["Tekken Tag Tournament HD","OOHRAAH - Clear Time Attack in under 06'00\"00.","http://www.playstationtrophies.org/images/trophies/1085/5DE.jpg"],
    ["The Walking Dead: Season 2","All Fall Down - Survived the attack.","http://www.playstationtrophies.org/images/trophies/3095/72e.jpg"],
    ["Transformers: Dark of the Moon","Homewrecker - Wipe out all secret base ground defenders within 60 seconds in Chapter V.","http://www.playstationtrophies.org/images/trophies/916/27.jpg"],
    ["Unreal Tournament III","Have a Nice Day - Get the \"Rocket Scientist\" award in 10 matches and \"Flak Master\" award in 10 matches.","http://www.playstationtrophies.org/images/trophies/108/024.jpg"],
    ["Wolfenstein: The New Order","Power to the Laser - Find the Laserkraftwerk","http://www.playstationtrophies.org/images/trophies/2552/434.jpg"],
    ["X-Men Origins: Wolverine","WoW! - You feel a cold as you examine the sword and skeleton. A rustle of wind in the trees faintly echoes the name Arthas","http://www.playstationtrophies.org/images/trophies/113/035.jpg"]
];

var tuffmuffList = [
    ["Battlefield: Bad Company","Manic Lumberjack - Knock down a small forest","http://www.playstationtrophies.org/images/trophies/55/022.jpg"],
    ["Battlefield: Bad Company 2","It's bad for my karma man! - Campaign: finish Heart of Darkness","http://www.playstationtrophies.org/images/trophies/326/04.jpg"],
    ["Battlefield 3","You can be my wingman anytime - Completed Going Hunting in a perfect run","http://www.playstationtrophies.org/images/trophies/883/13.jpg"],
    ["Battlefield 4","Shawshank - Get 5 kills with Shank in the Kunlun Mountains mission in the Campaign","http://www.playstationtrophies.org/images/trophies/2235/4E4.jpg"],
    ["Bejeweled 3","Relics Revealed - Unlock all 5 relics in Quest mode.","http://www.playstationtrophies.org/images/trophies/1110/010.jpg"],
    ["Call of Duty Classic","Old Glory - Complete the American Missions","http://www.playstationtrophies.org/images/trophies/277/25.jpg"],
    ["Call of Duty: Modern Warfare 2","Star 69 - Earn 69 stars in Special Ops.","http://www.playstationtrophies.org/images/trophies/240/36.jpg"],
    ["Call of Duty: Modern Warfare 3","Unstoppable - Reach Wave 15 in each mission of Special Ops Survival mode.","http://www.playstationtrophies.org/images/trophies/422/47.jpg"],
    ["Dante's Inferno","Poetry in Motion - Perform a 666 hit combo","http://www.playstationtrophies.org/images/trophies/322/28.jpg"],
    ["Dead to Rights: Retribution","Dog tag - Perform a tag team kill with Shadow","http://www.playstationtrophies.org/images/trophies/376/30.jpg"],
    ["Earth Defense Force: Insect Armageddon","Welcome to the EDF - Kill 1000 Ants; 1000? There must be a jillion of those things! Get busy!","http://www.playstationtrophies.org/images/trophies/754/03.jpg"],
    ["Fallout 3","Vault-Tec C.E.O. - Collected 20 Vault-Tec Bobbleheads","http://www.playstationtrophies.org/images/trophies/70/050.jpg"],
    ["Fallout: New Vegas","No Gods, No Masters - Completed No Gods, No Masters.","http://www.playstationtrophies.org/images/trophies/343/42.jpg"],
    ["Far Cry 3","Poker Bully - Win $1500 playing poker.","http://www.playstationtrophies.org/images/trophies/922/E55.jpg"],
    ["Far Cry 3: Blood Dragon","Derp - Jump Down from 50 Meters","http://www.playstationtrophies.org/images/trophies/2000/C46.jpg"],
    ["Hard Corps: Uprising","All Clear - [RISING MODE] Clear all missions","http://www.playstationtrophies.org/images/trophies/676/03.jpg"],
    ["Hunter's Trophy 2: Australia","Bad master - Having killed a dog","http://www.playstationtrophies.org/images/trophies/2272/CDE.jpg"],
    ["Killzone 3","Completist - Destroyed every destructible weapon on the MAWLR while on foot and on the Intruder","http://www.playstationtrophies.org/images/trophies/430/25.jpg"],
    ["Madden NFL 12","Arian Foster Award - Rush for 231+ yards in a game with one player (No OTP or co-op)","http://www.playstationtrophies.org/images/trophies/969/07.jpg"],
    ["My Aquarium","Breeding Novice - Bred successfully at least 5 times.","http://www.playstationtrophies.org/images/trophies/740/06.jpg"],
    ["Plants vs. Zombies","Alive and Planting - Survive 40 waves of pure zombie ferocity","http://www.playstationtrophies.org/images/trophies/901/06.jpg"],
    ["Portal 2","Asking for Trouble - Taunt GLaDOS in front of a camera in each of the five co-op courses","http://www.playstationtrophies.org/images/trophies/610/49.jpg"],
    ["Red Dead Redemption","Buckin' Awesome - Break the Kentucky Saddler, the American Standardbred, and the Hungarian Half-bred.","http://www.playstationtrophies.org/images/trophies/340/19.jpg"],
    ["Resistance 3","Slaybells - Make Santa and his reindeer fly","http://www.playstationtrophies.org/images/trophies/546/10.jpg"],
    ["Saints Row: The Third","Gender Equality - Play for at least 2 hours as a male character AND 2 hours as a female character.","http://www.playstationtrophies.org/images/trophies/746/37.jpg"],
    ["Sound Shapes","Death Mode: Galaxanoids - Complete the Death Mode level.","http://www.playstationtrophies.org/images/trophies/1076/5F0.jpg"],
    ["Starhawk","Only the Beginning... - Complete the campaign on Mercenary difficulty.","http://www.playstationtrophies.org/images/trophies/421/62D.jpg"],
    ["Super Hang-On","The Kiss of Fate - Cross the checkpoint with 1 second left.","http://www.playstationtrophies.org/images/trophies/1543/241.jpg"],
    ["The Elder Scrolls V: Skyrim","Words of Power - Learn all three words of a shout","http://www.playstationtrophies.org/images/trophies/826/46.jpg"],
    ["Voltron: Defender of the Universe","Blazing Victory - Kill a Robeast without Voltron losing any health.","http://www.playstationtrophies.org/images/trophies/920/A45.jpg"]
];

var vyrastasList = [
    ["Assassin's Creed II","Undertaker - Discover the Assassin's Tomb inside the catacombs under Santa Maria Novella","http://www.playstationtrophies.org/images/trophies/260/09.jpg"],
    ["Assassin's Creed Brotherhood","Plumber - Discover the Shrine in the Cloaca Maxima","http://www.playstationtrophies.org/images/trophies/362/19.jpg"],
    ["Back to the Future: The Game","Moonwalker - Busted a move, 80's style","http://www.playstationtrophies.org/images/trophies/1245/60.jpg"],
    ["Castlevania: Lords of Shadow","Brawler - Buy 15 combos","http://www.playstationtrophies.org/images/trophies/420/37.jpg"],
    ["Darksiders","Reaper - Collect the Scythe","http://www.playstationtrophies.org/images/trophies/276/22.jpg"],
    ["Dead Nation","Looter - Collect All The Loot In Any Mission","http://www.playstationtrophies.org/images/trophies/592/34.jpg"],
    ["Dead Space","Slugger - Kill the Slug Boss with more than 50% Shield strength remaining","http://www.playstationtrophies.org/images/trophies/26/039.jpg"],
    ["Dragon Age: Origins","Dragonslayer - Defeated the dragon guarding the Urn of Sacred Ashes","http://www.playstationtrophies.org/images/trophies/270/25.jpg"],
    ["Fallout 3","Protector - Reached Level 8 with Good Karma","http://www.playstationtrophies.org/images/trophies/70/033.jpg"],
    ["Final Fantasy XIII","Loremaster - Discerned the full attributes of 100 enemies","http://www.playstationtrophies.org/images/trophies/307/35.jpg"],
    ["God of War II","Swinger - Cross the collapsing Grapple Bridge","http://www.playstationtrophies.org/images/trophies/264/1.jpg"],
    ["God of War: Chains of Olympus","Cosplayer - Play the game with an unlocked costume","http://www.playstationtrophies.org/images/trophies/1068/34.jpg"],
    ["Heavy Rain","Butcher - The lizard, cut your finger using saw or scissors","http://www.playstationtrophies.org/images/trophies/321/26.jpg"],
    ["Hydrophobia Prophecy","Survivor - Completed the game","http://www.playstationtrophies.org/images/trophies/1006/01.jpg"],
    ["InFamous 2","Mountaineer - Climb to the top of the 3 tallest buildings in New Marais","http://www.playstationtrophies.org/images/trophies/571/27.jpg"],
    ["Lara Croft and the Guardian of light","Breadwinner - Earn the top score objective in any level","http://www.playstationtrophies.org/images/trophies/433/07.jpg"],
    ["Little Big Planet","Homemaker - Place 10 stickers or decorations in your pod","http://www.playstationtrophies.org/images/trophies/14/10.jpg"],
    ["Machinarium","Escaper - Escape Machinarium","http://www.playstationtrophies.org/images/trophies/1709/6AA.jpg"],
    ["Pac-Man Championship Edition DX ","Sparkster - Emit sparks for 1 second!","http://www.playstationtrophies.org/images/trophies/817/01.jpg"],
    ["Plants vs Zombies","Explodonator - Blast 10 zombies at once with a Cherry Bomb!","http://www.playstationtrophies.org/images/trophies/901/09.jpg"],
    ["Prince of Persia","Improviser - Use the environment against an enemy","http://www.playstationtrophies.org/images/trophies/59/017.jpg"],
    ["Ratchet & Clank: All 4 One","Pyromancer - Barbecue four enemies at the same time using the Pyro Blaster","http://www.playstationtrophies.org/images/trophies/704/19.jpg"],
    ["Rayman Origins","Explorer - You found 25 hidden cages","http://www.playstationtrophies.org/images/trophies/651/09.jpg"],
    ["Shift 2: Unleashed","Amateur - Reached Driver Level 5","http://www.playstationtrophies.org/images/trophies/696/02.jpg"],
    ["Sly Cooper: Thieves in Time","Gunslinger - Reunite with Sly's long lost Cooper relative in Episode 2","http://www.playstationtrophies.org/images/trophies/810/354.jpg"],
    ["Star Wars: The Force Unleashed","Destroyer - Complete Level - Raxus Prime, act 2","http://www.playstationtrophies.org/images/trophies/195/10.jpg"],
    ["The Unfinished Swan","Dreamer - Finish the King's Dream chapter","http://www.playstationtrophies.org/images/trophies/1530/E9E.jpg"],
    ["Tomb Raider Underworld","Roadkiller - Kill an enemy by running over it with the motorcycle","http://www.playstationtrophies.org/images/trophies/143/21.jpg"],
    ["Trine 2","Icebreaker - Shatter three frozen enemies within one second","http://www.playstationtrophies.org/images/trophies/601/005.jpg"],
    ["Velocity Ultra","Slacker - Beat the minesweeper minigame","http://www.playstationtrophies.org/images/trophies/2055/55E.jpg"]
];

var woodyList = [
    ["2010 FIFA World Cup","Lightning Quick Strike - Score in under 90 seconds to beat the standing record for fastest goal in a World Cup finals match.","http://www.playstationtrophies.org/images/trophies/381/42.jpg"],
    ["Batman: Arkham Asylum","Solitary Confinement - Capture and lock up Harley Quinn","http://www.playstationtrophies.org/images/trophies/192/11.jpg"],
    ["Batman: Arkham City","Contract Terminated - Stop the contract operative","http://www.playstationtrophies.org/images/trophies/398/17.jpg"],
    ["Batman: Arkham Origins","One eye open - Defeat Deathstroke","http://www.playstationtrophies.org/images/trophies/2009/004.jpg"],
    ["Bayonetta","A Mother's Love - Defend Cereza during the out of body experience, ensuring she takes no damage.","http://www.playstationtrophies.org/images/trophies/52/19.jpg"],
    ["Bioshock","Little Sister Savior - The player has completed the game without harvesting any Little Sisters","http://www.playstationtrophies.org/images/trophies/23/49.jpg"],
    ["Bioshock 2","Master Protector - Got through a Gather with no damage and no one getting to the Little Sister.","http://www.playstationtrophies.org/images/trophies/309/33.jpg"],
    ["Borderlands 2","Cool Story, Bro - Defeated Jack","http://www.playstationtrophies.org/images/trophies/1145/3D0.jpg"],
    ["Captain America: Super Soldier","And They All Fall Down - 4 Enemies KO'd with a single Focused Shield Throw","http://www.playstationtrophies.org/images/trophies/769/D85.jpg"],
    ["Contrast","To The Heroes Among Us - Unlocked when the player finds the hidden Extra Life 2012 Logo.","http://www.playstationtrophies.org/images/trophies/2114/00.jpg"],
    ["Far Cry 3","Worst Date Ever - Rescue Liza from the burning building.","http://www.playstationtrophies.org/images/trophies/922/04C.jpg"],
    ["FIFA 10","Grind it Out - Win a match with 10 men Online or when playing on Professional difficulty or higher","http://www.playstationtrophies.org/images/trophies/224/07.jpg"],
    ["FIFA 11","Once in a Lifetime - Score as the Goalkeeper in any match","http://www.playstationtrophies.org/images/trophies/589/27.jpg"],
    ["FIFA 12","Riding Bikes - Score with a bicycle kick","http://www.playstationtrophies.org/images/trophies/972/04.jpg"],
    ["FIFA 13","Trolling for Goals - Score on a free kick after running over the ball","http://www.playstationtrophies.org/images/trophies/1429/C30.jpg"],
    ["FIFA 14","Perfection - Score a Perfect Hat Trick (left foot, right foot, header)","http://www.playstationtrophies.org/images/trophies/1854/42B.jpg"],
    ["FIFA Street","Rush Keepers! - Score a goal while controlling your Goal Keeper","http://www.playstationtrophies.org/images/trophies/1152/9B9.jpg"],
    ["Green Lantern: Rise of the Manhunters","Emerald Warrior - Complete the game on Poozer of Enforcer difficulty.","http://www.playstationtrophies.org/images/trophies/679/13.jpg"],
    ["InFamous","Goody Two Shoes - Reach full positive Karma.","http://www.playstationtrophies.org/images/trophies/122/2.jpg"],
    ["InFamous 2","Incorruptible - Earn full positive Karma.","http://www.playstationtrophies.org/images/trophies/571/12.jpg"],
    ["InFamous: Second Son","True Hero - Achieve Level 5 Good Karma","http://www.playstationtrophies.org/images/trophies/1936/a42.jpg"],
    ["Injustice: Gods Among Us","True Marksman - Win a match with Green Arrow using only arrows","http://www.playstationtrophies.org/images/trophies/1572/88F.jpg"],
    ["Iron Man 2","The Bigger They Are - Defeat ULTIMO.","http://www.playstationtrophies.org/images/trophies/404/09.jpg"],
    ["Lightning Returns: Final Fantasy XIII","The Chocobo's Savior - Proof of nursing the holy chocobo back to full health among the rich pastures of the Wildlands.","http://www.playstationtrophies.org/images/trophies/1700/374.jpg"],
    ["Lollipop Chainsaw","San Romero Knights Savior - Rescued All Classmates.","http://www.playstationtrophies.org/images/trophies/1134/4D7.jpg"],
    ["Marvel vs. Capcom 3: Fate of Two Worlds","Avengers Assemble! - Make a team composed of the Big 3 and win a match. (Arcade/online only)","http://www.playstationtrophies.org/images/trophies/538/28.jpg"],
    ["Resogun","Denied! - Save a human from Abductor's beam","http://www.playstationtrophies.org/images/trophies/2229/17.jpg"],
    ["Sonic Generations","Action Hero - Perform all of Sonic's moves in Act 2.","http://www.playstationtrophies.org/images/trophies/999/29.jpg"],
    ["Star Wars: The Force Unleashed II","A Measure of Mercy - Complete the game and choose the Light Side ending","http://www.playstationtrophies.org/images/trophies/397/11.jpg"],
    ["X-Men Origins: Wolverine","The Dead Pool - Defeated Weapon 11 (Deadpool)","http://www.playstationtrophies.org/images/trophies/113/006.jpg"]
];